[package]
name = "licurs_sys"
version = "0.1.0"
edition = "2024"
links = "driverapi"
exclude = [
  "vendor/librecuda/tests"
]

[dependencies]

[build-dependencies]
bindgen = "0.71.1"
cmake = "0.1.54"
